DoliCloud/SellYourSaas

langs/en_US/sellyoursaas.lang, langs/es_ES/sellyoursaas.lang, langs/fr_FR/sellyoursaas.lang, myaccount/.gitignore, myaccount/index.php
Support multiple URL by cloud domain, example: 
- Other setup > **SELLYOURSAAS_SUPPORT_URL** > value "https://global.support.cloud"
- Other setup > **SELLYOURSAAS_SUPPORT_URL-domain1.cloud** > value "https://support.domain1.cloud"
- Other setup > **SELLYOURSAAS_SUPPORT_URL-domain2.cloud**  > value "https://help.domain2.cloud"
After declare other setup option, "Myaccount > Support" page displays a text inviting to follow the declared link:
=> feat(myaccount): add external support url option

myaccount/register_instance.php
=> FIX : email was not set when creating a new instance from user account

myaccount/index.php
Subservices of type "system" have a quantity that is calculated with a formula. Having their price in the global price of a plan is giving a false price.
=> Plan list price should not contain system option prices

scripts/remote_server_launcher.sh
"remote_server_launcher" service doesn't start anymore if we don't put the new var "remoteserverlistenport" in sellyoursaas configuration file.
```txt
systemd[1]: Starting LSB: Start/stop remote_server_launcher...
remote_server_launcher[22554]: **** /etc/init.d/remote_server_launcher
remote_server_launcher[22554]: Switch on directory /home/admin/wwwroot/dolibarr_sellyoursaas/scripts
remote_server_launcher[22554]: Server started with php -S 8080: -t remote_server remote_server/index.php
remote_server_launcher[22554]: Logs of server will be in /var/log/remote_server.log
systemd[1]: Started LSB: Start/stop remote_server_launcher.
remote_server_launcher[22554]: Invalid address: 8080:
```
introduced by https://github.com/eldy/sellyoursaas/commit/6f126be191c9bd7b48fed3816e9fcf73bf45a7e6#diff-bbd …
=> fix(remote_server): incorrect default variable name for listenport

myaccount/register.php
Just because of this php message : PHP Warning:  Cannot modify header information - headers already sent by (output started at .../... mainmyaccount.inc.php:315) in .../... register.php on line 243
=> set cookie before sending headers

myaccount/antispamimage.php
Array or string offset access with curly braces deprecated in PHP 7.4. Targeting PHP 8.0.0.
=> remove deprecated php7.4

class/packages.class.php
Leads to a fatal error when cloning a package
=> Fix : Missing const STATUS_DRAFT

admin/setup.php, langs/en_US/sellyoursaas.lang, myaccount/register.php, myaccount/register_instance.php, myaccount/tpl/support.tpl.php
Add an option SELLYOURSAAS_ONLY_NON_PROFIT_ORGA into sellyoursaas setup.
When option is set to ON, we include a message with a checkbox on the form to register.
"I confirm that I am not a non-profit institution. For commercial companies, an identical paying service is available on https://www.dolicloud.com/"
Also, when a user go on the support service, when this option is set, the fields to send the ticket email are hidden (the field "Select your channel must not be visible, sender email and email topics, join files and textarea are also hidden),
Only the fields to select the category of ticket and the suggested FAQ that appears after must works.
=>  Close #209 : add of option SELLYOURSAAS_ONLY_NON_PROFIT_ORGA 

admin/setup.php, myaccount/register_instance.php
@eldy 
Allows you to block specific email addresses or domain names (@name.net) not managed by "DisposableEmail" and often a generator of fake accounts (eg gmail.com)
=> FIX broken feature

doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc, doc/Documentation SellYourSaas - Master and Deployment Servers - FR.asciidoc
Update github URI + add git clone option to get only stable branch (for example 15.0)
=> do not clone master dolibarr branch

core/lib/dolicloud.lib.php
Without it, files end up in the parent directory of the intended target.
More explicit instructions could be useful too (such as which directory the command should be run from), but this is already very helpful.
=> FIX: missing htdocs/ in target path for rsync command (for restoring programs)

doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc, doc/Documentation SellYourSaas - Master and Deployment Servers - FR.asciidoc
The Apache VirtualHost configuration for MyAccount as prescribed by the documentation does not allow the apache process to access /usr/share/GeoIP, where the geoip database is usually located.
Note: as an alternative to GeoIP, we could also use this bit of js for operators who don't want to use GeoIP, @eldy do you think it would be a good idea?
- Pros : works better for users with a VPN whose public IP is in a different country (unless the users deliberately change their timezone on the OS level or using a browser extension / feature).
- Cons : the server-side method using GeoIP is better for users without javascript or with older browsers that don't implement Intl.
I think both methods could even be used together (one being the fallback of the other).
```javascript
// time zone data from …
```
=> FIX: country detection (GeoIP) inoperative on registration pages

myaccount/register.php
The option name says "HIDE" but it currently shows the phone number when it is on (and hides it when the option is off).
Another possibility would be to rename the option `SELLYOURSAAS_REGISTER_SHOW_PHONE`, but I like it better with HIDE being the option.
=> FIX counter-intuitiveness of SELLYOURSAAS_REGISTER_HIDE_PHONE

scripts/action_upgrade_instance.sh
Tested this with updating from one minor version to the next (i.e. from 16.0.3 to 16.0.4) and also updating from a minor to the next major version (form 16.0.4 to 17.0.0). In this case, technically there is one superfluous step going from 17.0.0 to 17.0.x, which is not doing any harm.
The logging is not quite right, because it does not explicitly print the minor version in the last run, but rather the next major version.
=> Fix: #281 (action upgrade also for change in minor version)

scripts/batch_customers.php
Found as part of the investigation of the impact of https://wiki.php.net/rfc/saner-inc-dec-operators
This pair of assignments happens else where in this file and assigns ``$error`` to 0.
=> Fix incorrect empty string assignment to $error instead of 0

myaccount/register.php
Currently, there is a mechanism to request acceptance of terms and conditions in a special way, if the host is dolicloud.com.
I added a generic mechanism, which will not affect the existing one:
If the variable SELLYOURSAAS_TERMSANDCONDITIONS is set with the name of the T&C page (e.g. terms.php), a checkbox is shown on the registration page to accept the terms and conditions and a link is provided to this page. Accepting this checkbox is mandatory to proceed, if it is shown. This is the last item on the page (after newsletter acceptance and optional non profit orga checkbox).
The message for the checkbox is stored under the key WhenRegisteringYouAccept (same as for the dolicloud specific mechanism to show T&C pages).
Screenshot (sorry, at the moment only in German available):
=> NEW: Option to request acceptance of terms and conditions during sign-up of new user

scripts/perms.ksh
Helps ensure that all crontabs have the correct owners and permissions.
=> feat(perms): force owners+chmod for all crontabs

myaccount/tpl/action_create_recinvoice_after_payment_creation.tpl.php
A fatal error trigger when trying to set a field in a variable that is null
=> Fix fatal error while creating rec invoice after payment creation

scripts/backup_backups.php
The port specification from config file was not used for rsync with destination server.
=> Fix: use specified port for remote backup server

doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc, doc/Documentation SellYourSaas - Web portal - EN.asciidoc, scripts/backup_pull_backups.sh
It looks like the script, which was previously a shell script, was rewritten in PHP.
Documentation and other scripts should be changed accordingly.
Also existing root's crontabs have to be updated by administrators once they pull the new version of SellYourSaas, otherwise remote backups will stop working. I don't know if there is a mechanism for automating this? Like a git post-checkout hook that would call a SellYourSaaS script and tell the administrator what they should do?
=> FIX rename backup_backups.sh -> backup_backups.php in documentation and scripts

scripts/backup_backups.php
SellYourSaas seems to be aware of the issue already, but the current detection method (using Ubuntu version) is less reliable than using `rsync --help` and see if the option is described in the help text.
However, I am not used to executing shell commands from PHP and not comfortable with using the captured stdout. I'm open to better methods (like detecting rsync capabilities only once at install time, in an actual shell script, and storing the detection result in `sellyoursaas.conf` or any convenient place).
=> FIX: with some versions of rsync, option --noatime fails

myaccount/tpl/support.tpl.php
Prevent the user to be on support page with all the fields filled after a email sent if the constant SELLYOURSAAS_ONLY_NON_PROFIT_ORGA is set
=> Fix support to prevent a bad workaround with non profit orga

myaccount/index.php, myaccount/tpl/autoupgrade.tpl.php
Add 2 new metrics for datadog:
- When an instance is successfully upgraded
- When a ticket is successfully sent on support
=> New datadog metrics for upgrade and ticket send on support

myaccount/tpl/instances.tpl.php
After calling $websitestatic->fetchAll (line 795),  the variable $listofwebsitestoactivate contains the number of websites. The data of the websites, over which we need to iterate, is stored in the property $webistestatic->records.
=> Fix bug in creating custom URL for CMS websites with SellYourSaaS

scripts/action_website_instance.sh
If the website name did not start with www. a wrong path was used (missing 'documents/' in filepath).
=> Fix: Error generating certfile for website

backoffice/instance_users.php
This PR adds the call to the deleteSupportUser hook in the SellYourSaaS module to allow other modules to manage additional actions before deleting a support user. By using this hook, other modules can intervene to check and resolve constraints that may prevent the deletion of the user, such as data dependencies or entries associated with other tables.
If constraints prevent the deletion of the support user, the action will not be performed, and an error message will be displayed to the user:
This website or feature is currently temporarily not available or failed after a technical error. This may be due to a maintenance operation. Current status of operation (2025-03-25T11:02:08Z) are on next line...
This allows flexible and modular management of support users across Dolibarr, …
=> New hook delete support user

doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
`/home/admin/wwwroot/dolibarr_documents/sellyoursaas/spam` is per documentation created on the deployment server on a path that later becomes the NFS mount. On the master we are writing files in this directory, which at that point doesn't exist, since the instructions create it on the deployment server. This fixes it.
=> Create spam directory on master, not on deployment server
