- etc/sellyoursaas.conf
- scripts/clean.sh
As discussed yesterday, the script works very well !
> Add vars in sellyoursaas.conf to be used by clean.sh

- doc/Documentation SellYourSaas - Master and Deployment Servers - FR.asciidoc
[*Perfectionnement du texte, une fois fait, ce sera à vie.*]
> Fix : correction de la documentation

- myaccount/index.php
- myaccount/tpl/support.tpl.php
New you can upload files on the support form request
> Fix #93 upload files on support request form

- myaccount/tpl/support.tpl.php
Add a check on input file in support template
> Fix #101 : Add message when file not upload on support

- class/sellyoursaasutils.class.php
add a new entry to substitarray
> add __CONTRACTREF__ on substitarray

- class/sellyoursaasutils.class.php
add new keyword "phpmethod" to remote refresh action, then you can build your own php code (not only sql or bash)
> add PHPMETHOD keyword for refresh remote action

- myaccount/index.php
- myaccount/tpl/myaccount.tpl.php
New field phone number in contact informations
> Close #112 : new field phone in myaccount form

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
Fixing some typos in the English version of the
Master and Deployment Servers asciidoc
> Fix Fixing typos in the doc

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
Parts of the doc remain in FR to this day.
This is a first commit to convert fully to EN.
> Translation FR-to-EN

- fetchKnowledgeRecord.php
- myaccount/tpl/support.tpl.php
New connection between suport.tpl and knowledge records print a string if knowledge record found
> Close #121 : connection knowledge record & category

- myaccount/tpl/support.tpl.php
New list of tickets in support.tpl
> New : List of ticket in support tpl

- backoffice/instance_users.php
Migrate code of page sellyoursaas/backoffice/instance_users.php to use part of template of modulebuilder to show the array of users so we will be able to sort on columns and to choose which field to show.
> Close #120 : migration of page instance_users

- myaccount/ajax/fetchKnowledgeRecord.php
- myaccount/tpl/support.tpl.php
Add knowledge record url and question after choosing a category of ticket
> New : support category with url

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
To tell about switching accounts
> sys/sudo Updating the doc

- myaccount/tpl/support.tpl.php
Update of support.tpl.php in the  ticket category to match update of selectGroupTicket
> Update of support.tpl.php ticket category

- scripts/action_deploy_undeploy.sh
- scripts/action_suspend_unsuspend.sh
- scripts/backup_backup_backups.sh
- scripts/backup_backups.sh
- scripts/backup_mysql_system.sh
- scripts/clean.sh
- scripts/clean_remotebackup.sh
- scripts/firewallsellyoursaas.sh
- scripts/firewallsellyoursaasufw.sh
- scripts/make_instances_offline.sh
- scripts/perms.ksh
- scripts/post_inst_script.sh
- scripts/repair.ksh
Error codes values have been set to different
values to be able to quickly locate errors
in longer scripts
> New scripts/error-codes values

- myaccount/ajax/fetchKnowledgeRecord.php
- myaccount/tpl/support.tpl.php
Update fetchKnowledgeRecord and index.php to use lang in support form
> Update support form for lang use

- myaccount/tpl/support.tpl.php
fix KM links in support.tpl.php
> FIx : KM links in support.tpl.php

- myaccount/tpl/support.tpl.php
fix quote and double quote support.tpl
> fix quote and double quote support.tpl

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
- scripts/letsencrypt_authenticator.sh
Updated the doc about  the wildcard certificates
> Lets encrypt automation

- core/modules/modSellYourSaas.class.php
> fix warning

- scripts/ansible/create_user.yml
- scripts/ansible/deactivate_user.yml
- scripts/ansible/reactivate_user.yml
- scripts/ansible/remove_user.yml
Ansible scripts to add/remove/deactivate users
> New User management scripts

- myaccount/register.php
Here is a new layout for register page
It can be activated by using &customregister=1 in url to the page url
If the parameter needs to change name say it and it will be done
Screenshot for computer version:
Screenshot for mobile version:
> New layout for register page

- scripts/ansible/create_user.yml
- scripts/ansible/remove_user.yml
For the user creation file, as well as remove it
upon user removal
> New Add IP to Ansible user management files

- myaccount/dist/css/exemple.css
- myaccount/register.php
- myaccount/styles.css.php
Add of custom css feature for registration in a better way
> Fix custom css layout

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
Updated a few sentences to clarify them.
> Fix install documentation

- class/sellyoursaasutils.class.php
SQL request add a new check on payment mode to exclude not-stripe invoices
> fix #196: filter on payment mode = stripe

- myaccount/tpl/support.tpl.php
We hide lower part of support form while any group ticket is selected
> New : suppport form normaly hidden

- admin/setup.php
- langs/en_US/sellyoursaas.lang
Add of select in sellyoursaas conf to choose auto-migration ticket code
> New : select automigration code in conf

- core/modules/modSellYourSaas.class.php
- langs/en_US/sellyoursaas.lang
- myaccount/index.php
- myaccount/tpl/instances.tpl.php
New feature : creation of a from when uninstallation of instance is desired
> Close #190 : Add form on uninstall

- myaccount/tpl/automigration.tpl.php
- scripts/remote_server/index.php
Remove csrf error on submit of step 5 form
> Fix : remove csrf error on step5 aumigration

- scripts/remote_server/index.php
rename migrate_instance.sh to action_migrate_instance.sh and upgrade_instance.sh to action_upgrade_instance.sh in remote_server.php
> Fix remote_action name in remote_server

- admin/setup_other.php
- class/sellyoursaasutils.class.php
- langs/en_US/sellyoursaas.lang
- myaccount/index.php
- Add the possibility to add sepa payments method to client stripe account when user input it in registerpaymentmethod template
- Add possibility to use sepa payment if sepa has been added to client stripe account and the stripe sepa direct debit is activated
> New : add connection sellyoursaas <> stripe for sepa

- backoffice/deployment_servers.php
- langs/en_US/sellyoursaas.lang
Add some actions to deployment_server.php :
- Add new server to the deployment server list if the user can add/edit
- Edit a server from the deployment server list if the user can add/edit (Blue square)
- Remove a server from deployment server list if the user can delete (Red square)
> New : page deployment_server

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
- doc/Documentation SellYourSaas - Master and Deployment Servers - FR.asciidoc
- doc/Documentation SellYourSaas - Web portal - EN.asciidoc
- scripts/master_move_instance.php
- scripts/master_redeploy_instance.php
sometime there is mysaasdomain.com and sometime mysaasdomainname.com, that PR is just a search&replace all mysaasdomain -> mysaasdomainname to be coherent (and be able to change with a sed syscall)
> mysaasdomainname everywhere

- backoffice/instance_links.php
FIX possibility to see "last install" and "last upgrade"
> Fix missing substitution for sql formula

- myaccount/styles.css.php
- myaccount/tpl/support.tpl.php
> Fix : upgrade css + js

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
minor formatting improvements to asciidoc and clarification
> fix: some fixes to doc

- core/modules/modSellYourSaas.class.php
- langs/en_US/sellyoursaas.lang
- langs/fr_FR/sellyoursaas.lang
- myaccount/register_instance.php
Add save of an optional field to know if a third party is a non profit organization
> New : add save of checkbosnonprofitorga var on thirdparty

- myaccount/index.php
Hide password on instance creation welcome + add eye picto to show / hide password
> New : hide password on instance creation welcome

- myaccount/tpl/instances.tpl.php
Can force country on instance page
> Can force country on instance page

- backoffice/instance_links.php
I don't know if you prefer to change documentation (languages files) or php/sql but there is something incompatible between the two :)
> to be compatible with VersionFormulaExamples (translations)

- myaccount/index.php
- myaccount/register.php
fix validation process of free contracts + bad value for checkboxnonprofitorga
> Fix : validation process of free contracts

- myaccount/tpl/action_create_recinvoice_after_payment_creation.tpl.php
Fix fatal error in myaccount/tpl/action_create_recinvoice_after_payment_creation.tpl.php that trigger when $sellyoursaasutils is null
> Fix : action_create_recinvoice fatal error

- class/sellyoursaasutils.class.php
Make doValidateDraftInvoices renew contract of direct debit SEPA payment mode invoices.
Before call :
After call :
> Fix : doValidateDraftInvoices to renew contract of direct debit SEPA payment mode invoices

- myaccount/index.php
Fix reseller application form to concatenate mail content to note_private and redirect to index page
> Fix reseller application form

- doc/Documentation SellYourSaas - Master and Deployment Servers - EN.asciidoc
add doc to change root password for OVH users
> New add how to change root password for ovh

- myaccount/register_instance.php
Same authorization as for "TooManyInstancesForSameIp".
> fix: whitelisted IP bypass too many hourly deployment

- scripts/backup_backups.php
Migrate the script backup_backups.sh to php code
> New migrate backup_backups.sh to php

- scripts/backup_backups.php
Fix script backup_backups.php so we can use it in crontab
> Fix script backup_backups.php

- myaccount/tpl/support.tpl.php
Fix an error where if ticket was never enabled create a database error
> Fix support page db error

- langs/en_US/sellyoursaas.lang
- langs/fr_FR/sellyoursaas.lang
- myaccount/tpl/instances.tpl.php
Fix option part for website option to match custom url part
> Fix instance page website option part

- myaccount/index.php
- scripts/action_customurl_instance.sh
Permit creation of custom url for user. Certificate ssl creation error
> New script custom url

- myaccount/index.php
- myaccount/tpl/instances.tpl.php
add verification on options website install to verify if a website has been already activated
> New verify if website activated application

- myaccount/tpl/instances.tpl.php
Fix bugs where you cannot use instance options if more than 1 instance in instance tab
> Fix some instance tpl errors and bugs

- scripts/action_customurl_instance.sh
Fix till the certbot part works to prevent any errors
> Fix action_customurl while certbot not working

- myaccount/index.php
- scripts/action_suspend_unsuspend.sh
We change custrom url installation with rename remote action
> Fix modify rename remote acion to generate cert

- class/deploymentserver.class.php
- deploymentserver_note.php
- lib/sellyoursaas_deploymentserver.lib.php
- sql/dolibarr_allversions.sql
- sql/llx_sellyoursaas_deploymentserver.sql
Add a note field in deployment server object that is visible in list
> New add note on deploymentserver object

- lib/sellyoursaas.lib.php
Add function to permit a minimum user number for an instance to set in line qty.
Take the max of (extrafield with code qtymin , qty on the contract line and nb user in customer database).
The extrafield with code qtymin must be created to use use this function else it will use the customer database anyway
> New function user contract

- myaccount/index.php
Add ip of user in support mail
> New User IP in support mail

- class/deploymentserver.class.php
- class/sellyoursaasutils.class.php
- deploymentserver_card.php
- langs/en_US/sellyoursaas.lang
- sql/dolibarr_allversions.sql
- sql/llx_sellyoursaas_deploymentserver.sql
Add the possibility to add a specific signature key for each deployment server
> New Add signature key for specific deployment server

- class/sellyoursaasutils.class.php
- lib/sellyoursaas.lib.php
Fix to use contract object instead of ref if using __OBJECTREF__ param
> Fix sellyoursaasGetNbUsersContract to use contract

- backoffice/instance_users.php
When creating the support user we add a specific private note with the default langage of the customer
> New support user creation add private note with customer lang

- class/sellyoursaasutils.class.php
Add a test on refresh remote action to update only if a data has been modify
> New add test on update for refresh actionb

- myaccount/register_instance.php
fix remove of already set categories on customers
> fix setCategories will remove all other tags of a customer :-( #361

- core/boxes/box_sellyoursaas_backup_errors.php
- core/modules/modSellYourSaas.class.php
- langs/en_US/sellyoursaas.lang
New box to see the backup errors local or remote in a widget
> New box sellyoursaas backup

- core/boxes/box_sellyoursaas_backup_errors.php
Fix style of box backup error to match the general style
> Fix style of box backup error

- sql/llx_sellyoursaas_deploymentserver.sql
[…ver table creation](fix:missing field in sql statement for llx_sellyoursaas_deploymentserver table creation)
> fix:missing field in sql statement for llx_sellyoursaas_deploymentserver table creation

- myaccount/tpl/dashboard.tpl.php
If 0 due and no invoicetopay we hide remaining to pay
> New hide remaining to pay if 0 due

- scripts/action_suspend_unsuspend.sh
Fix an error in rename process with custom url that result in a bad virtualhost creation  + no certificate
> Fix erros in rename action for custom url creation

- scripts/remote_server/index.php
Added patterns to allow mkdir and cp in the CLI script after deploy
> NEW added patterns for CLI after deploy

- myaccount/index.php
I believe that the setting SELLYOURSAAS_EXTCSS is not taken into account currently. I added the ability to do so.
> Take SELLYOURSAAS_EXTCSS  into account

- myaccount/tpl/automigration.tpl.php
fix uncompress for gzip and bzip in automigration process
> Fix bad uncompress for gzip and bzip in automigration

- langs/en_US/sellyoursaas.lang
- myaccount/register.php
Add a select in register page when we have more then one plan in parameter like PlanA,PlanB or PLanA;PLanB
The select is required and set to empty by default
> New add select for plan in register page

- README.md
This PR improves the README for better clarity, structure, and readability:
- 🧩 Moved the **Overview** section directly below the title for stronger first impressions
- ✍️ Rewrote the Overview content to clearly explain the project’s value and purpose
- 📑 Added a clickable **Menu** (Table of Contents) with anchor links to key sections
- ✅ Cleaned up grammar, improved consistency (e.g., standardized "SaaS" casing)
- 🧹 Removed the unused Screenshots section for simplicity
- 📦 Grouped features under meaningful categories for easier scanning
These changes aim to make the repository more accessible for new users, contributors, and potential adopters.
Looking forward to your feedback!
> Enhance README: Clearer Overview, Structured Menu, and Improved Formatting

- admin/setup_deploy_dolibarr.php
- admin/setup_other.php
- langs/en_US/sellyoursaas.lang
- lib/sellyoursaas.lib.php
Move Dolibarr custom URL and Dolibarr CMS constant setup in a new page setup_deploy_dolibarr.php
> New setup page deploy dolibarr

- langs/en_US/sellyoursaas.lang
- myaccount/index.php
- myaccount/tpl/mymodulecustomerbilling.tpl.php
- myaccount/tpl/mymodulecustomerinstances.tpl.php
Implements tpl pages for module supplier.
> New implements billing and instance page for module supplier
